# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db98e2e0ee9809a3f69410c74d61bb17d22499c0aeccd500185a6839e548ea3a113f27e2fe5214c372bbfc82f1377538b33d0181c6d2f04f8f17fc2633d0c5fd

test:
  secret_key_base: 24df7a467dd76d183fc7fe8ff194e2c6f26cbecc053962aa20a256074d48c024c20face3024fa865b728a1576020b5f934d79d900097eb4f9ec2cf240e3a74c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
